Repository nocox/asakatu-kun, pull requests merged in 2019-10, with the labels that each got.

#173 [IR]profileImage取れるようにしたよ
  vue/package-lock.json
  vue/src/App.vue
  vue/src/components/Header.vue
  vue/src/main.js
  vue/src/static/logo.png
  vue/src/views/Home.vue
  vue/src/views/Login.vue
Labels: ReviewWanted, vue

#135 [IR]フロントバリデーションを修正します
  springboot/pom.xml
  springboot/src/main/java/com/asakatu/controller/UserRegistrationController.java
  springboot/src/main/java/com/asakatu/entity/USER_REGISTRATION_ERROR.java
  springboot/src/main/java/com/asakatu/exeptions/UserAlreadyExistException.java
  springboot/src/main/java/com/asakatu/exeptions/UserRegistrationException.java
  springboot/src/main/java/com/asakatu/repository/UserRepository.java
  springboot/src/test/java/com/asakatu/UserRegistrationControllerTests.java
  vue/.eslintrc.js
  vue/package-lock.json
  vue/src/assets/css/_login-signup.scss
  vue/src/views/Login.vue
  vue/src/views/SignUp.vue
Labels: ReviewWanted, fronteEnd, vue

#179 test: UserRegistrationControllerTestsを修正
  springboot/src/test/java/com/asakatu/UserRegistrationControllerTests.java
Labels: ReviewWanted

#192 Fix/login redirect and header
  vue/src/components/Header.vue
  vue/src/views/Login.vue
Labels: ReviewWanted

#181 store_nameを追加
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/entity/Event.java
  springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
  springboot/src/main/resources/schema-product.sql
  springboot/src/test/java/com/asakatu/EventControllerTests.java
  springboot/src/test/resources/data-product.sql
  vue/src/views/EventCreate.vue
Labels: ReviewWanted

#180 Add/event detail
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/entity/Event.java
  springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
  springboot/src/main/resources/schema-product.sql
  springboot/src/test/java/com/asakatu/EventControllerTests.java
  springboot/src/test/resources/data-product.sql
  vue/src/views/EventCreate.vue
Labels: ReviewWanted
