Repository nocox/asakatu-kun, pull requests merged in 2019-09, with the labels that each got.

#113 [IR]/events関連の形式が違う修正
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/entity/Event.java
  springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
  springboot/src/main/java/com/asakatu/repository/EventRepository.java
  springboot/src/main/java/com/asakatu/response/ForFrontEvent.java
  springboot/src/main/java/com/asakatu/response/GetEventsListResponse.java
  springboot/src/main/java/com/asakatu/service/PostService.java
  springboot/src/test/java/com/asakatu/EventControllerTests.java
Labels: ReviewWanted

#106 [IR]ユーザーステータスAPI+編集API実装
  springboot/src/main/java/com/asakatu/controller/UserStatusController.java
  springboot/src/main/java/com/asakatu/entity/User.java
  springboot/src/main/java/com/asakatu/repository/UserStatusRepository.java
  springboot/src/test/resources/data-product.sql
Labels: ReviewWanted, backEnd

#128 ログイン周りのデザインを適応
  vue/src/App.vue
  vue/src/assets/css/_login-signup.scss
  vue/src/components/HelloWorld.vue
  vue/src/views/Login.vue
  vue/src/views/SignUp.vue
Labels: HTML/CSS, fronteEnd, vue

#126 [IR]イベント名がない修正
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/entity/Event.java
  springboot/src/main/resources/schema-product.sql
  springboot/src/test/java/com/asakatu/EventControllerTests.java
  springboot/src/test/resources/data-product.sql
Labels: backEnd

#123 [IR] リアクションの表示と変更
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/controller/ReactionController.java
  springboot/src/main/java/com/asakatu/controller/UserDetailController.java
  springboot/src/main/java/com/asakatu/controller/UserRegistrationController.java
  springboot/src/main/java/com/asakatu/entity/UserStatusMaster.java
  springboot/src/main/java/com/asakatu/exeptions/FileStorageException.java
  springboot/src/main/java/com/asakatu/property/S3ProfileImageProperties.java
  springboot/src/main/java/com/asakatu/property/S3ReactionImageProperties.java
  springboot/src/main/java/com/asakatu/repository/UserStatusMasterRepository.java
  springboot/src/main/java/com/asakatu/response/GetListResponse.java
  springboot/src/main/java/com/asakatu/response/ObjectResponse.java
  springboot/src/main/java/com/asakatu/service/ProfileImageService.java
  springboot/src/main/java/com/asakatu/service/S3BucketService.java
  springboot/src/main/resources/application.yml
  springboot/src/main/resources/schema-product.sql
  springboot/src/test/java/com/asakatu/ReactionControllerTests.java
  springboot/src/test/resources/data-product.sql
  vue/src/components/UserReaction.vue
  vue/src/router.js
  vue/src/store.js
  vue/src/views/ComponentDemo.vue
Labels: backEnd

#148 [IR] ログインが正常に動作するように修正
  vue/src/store.js
  vue/src/views/Login.vue
  vue/src/views/MyPage.vue
Labels: fronteEnd

#161 [IR] イベント作成ページ(vue)の側だけ作る
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/entity/Event.java
  springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
  springboot/src/main/java/com/asakatu/service/PostService.java
  vue/src/views/EventCreate.vue
Labels: ReviewWanted

#159 同じユーザが同じイベントに参加できないようにした
  springboot/src/main/java/com/asakatu/controller/EventController.java
  springboot/src/main/java/com/asakatu/repository/EventRepository.java
  springboot/src/main/resources/schema-product.sql
Labels: ReviewWanted

#156 [IR] headerをcomponentにしたよ
  vue/src/components/header.vue
  vue/src/views/Home.vue
Labels: vue

#160 イベント作成時のテストを作成
  springboot/src/main/java/com/asakatu/property/FromFrontEventProperties.java
  springboot/src/main/java/com/asakatu/repository/EventRepository.java
  springboot/src/test/java/com/asakatu/EventControllerTests.java
Labels: ReviewWanted
